--Q5: List All the Customers Living in NAGPUR and Having the Branch City as MUMBAI or DELHI

SELECT CUS.CNAME FROM CUSTOMER AS CUS WHERE CUS.CITY='NAGPUR' AND CUS.CNAME IN (SELECT DP.Cname FROM Deposit AS DP WHERE DP.Bname IN (SELECT BR.BNAME FROM BRANCH AS BR WHERE BR.CITY='MUMBAI' OR BR.CITY='DELHI'))