--Assignment:

--[1] Get difference between JOINING_DATE and INCENTIVE_DATE from employee and incentives table

SELECT EMP.FIRST_NAME,Date_Difference=JOINING_DATE-CAST(INCENTIVE_DATE AS DATETIME) FROM Employee AS EMP INNER JOIN Incentives AS INS 
ON EMP.EMPLOYEE_ID=INS.EMPLOYEE_REF_ID

--Another Way
SELECT EMP.FIRST_NAME,Date_Difference=JOINING_DATE-CAST(INCENTIVE_DATE AS DATETIME) FROM Employee AS EMP RIGHT JOIN Incentives AS INS 
ON EMP.EMPLOYEE_ID=INS.EMPLOYEE_REF_ID
